"""
Checkout, tickets, and the gate: everything after a seat is held.

A payment creates exactly one booking however many times its webhook
arrives, tickets are generated by the background worker, and a QR code
admits exactly one person, even when several gates scan it at the same
moment.
"""

from concurrent.futures import ThreadPoolExecutor

import pytest

from helpers import auth_headers


# ---------------------------------------------------------------------------
# Payments
# ---------------------------------------------------------------------------

def _checkout(client, token, seat_id):
    """Helper to hold a seat and initiate checkout."""
    client.post(f"/api/seats/{seat_id}/lock", headers=auth_headers(token))
    return client.post(
        "/api/payments/checkout", json={"seat_id": seat_id}, headers=auth_headers(token)
    )


def test_checkout_moves_seat_to_payment_pending(client, tokens, free_seat):
    """After checkout, the seat moves past the hold state but is NOT booked."""
    seat_id = free_seat["id"]

    res = _checkout(client, tokens[0], seat_id)
    assert res.status_code == 201
    assert res.json()["provider"] in ("mock", "stripe")

    seat = client.get(f"/api/seats/{seat_id}").json()
    assert seat["status"] == "payment_pending"

    # ⭐ Most important: no booking created yet
    mine = client.get("/api/bookings", headers=auth_headers(tokens[0])).json()
    assert not [b for b in mine if b["seat_id"] == seat_id and b["status"] == "confirmed"]


def test_another_user_cannot_checkout_held_seat(client, tokens, free_seat):
    """One user's hold prevents another's checkout — 409."""
    seat_id = free_seat["id"]
    _checkout(client, tokens[0], seat_id)

    res = client.post(
        "/api/payments/checkout", json={"seat_id": seat_id}, headers=auth_headers(tokens[1])
    )
    assert res.status_code == 409


def test_successful_payment_creates_exactly_one_booking(client, tokens, free_seat):
    """Happy path — payment succeeds, booking created, seat booked."""
    seat_id = free_seat["id"]
    token = tokens[0]

    payment_id = _checkout(client, token, seat_id).json()["payment_id"]

    res = client.post(
        f"/api/payments/{payment_id}/simulate",
        json={"outcome": "success"},
        headers=auth_headers(token),
    )
    assert res.status_code == 200
    body = res.json()
    assert body["status"] == "succeeded"
    assert body["booking_id"] is not None

    assert client.get(f"/api/seats/{seat_id}").json()["status"] == "booked"

    mine = client.get("/api/bookings", headers=auth_headers(token)).json()
    confirmed = [b for b in mine if b["seat_id"] == seat_id and b["status"] == "confirmed"]
    assert len(confirmed) == 1


def test_fulfilment_is_idempotent(client, tokens, free_seat):
    """
    ⭐ Webhooks are AT-LEAST-ONCE — the gateway may send the same event twice.
    The second request should return the existing booking, not create a new one.
    """
    seat_id = free_seat["id"]
    token = tokens[0]

    payment_id = _checkout(client, token, seat_id).json()["payment_id"]

    first = client.post(
        f"/api/payments/{payment_id}/simulate",
        json={"outcome": "success"},
        headers=auth_headers(token),
    ).json()

    second = client.post(
        f"/api/payments/{payment_id}/simulate",
        json={"outcome": "success"},
        headers=auth_headers(token),
    ).json()

    assert first["booking_id"] == second["booking_id"], "A new booking was created on the second attempt!"

    # Only one in the DB
    mine = client.get("/api/bookings", headers=auth_headers(token)).json()
    assert len([b for b in mine if b["seat_id"] == seat_id and b["status"] == "confirmed"]) == 1


def test_failed_payment_releases_the_seat(client, tokens, free_seat):
    """Payment failure — seat released, no booking created."""
    seat_id = free_seat["id"]
    token = tokens[0]

    payment_id = _checkout(client, token, seat_id).json()["payment_id"]

    res = client.post(
        f"/api/payments/{payment_id}/simulate",
        json={"outcome": "fail"},
        headers=auth_headers(token),
    ).json()
    assert res["status"] == "failed"
    assert res["booking_id"] is None

    assert client.get(f"/api/seats/{seat_id}").json()["status"] == "available"

    mine = client.get("/api/bookings", headers=auth_headers(token)).json()
    assert not [b for b in mine if b["seat_id"] == seat_id and b["status"] == "confirmed"]


def test_cannot_see_or_settle_someone_elses_payment(client, tokens, free_seat):
    """IDOR — prevent viewing or settling another user's payment."""
    seat_id = free_seat["id"]
    payment_id = _checkout(client, tokens[0], seat_id).json()["payment_id"]

    attacker = auth_headers(tokens[1])
    assert client.get(f"/api/payments/{payment_id}", headers=attacker).status_code == 404
    assert client.post(
        f"/api/payments/{payment_id}/simulate", json={"outcome": "success"}, headers=attacker
    ).status_code == 404


def test_webhook_rejects_bad_signature(client):
    """
    ⭐ Webhook endpoint is not authenticated — the signature is the only auth.

    Without this, anyone could POST and claim a free ticket.
    """
    res = client.post(
        "/api/payments/webhook",
        content=b'{"type":"checkout.session.completed"}',
        headers={"stripe-signature": "t=1,v1=deadbeef"},
    )
    assert res.status_code == 400


def test_webhook_without_signature_is_rejected(client):
    res = client.post("/api/payments/webhook", content=b"{}")
    assert res.status_code == 400


# ---------------------------------------------------------------------------
# Tickets (background worker)
# ---------------------------------------------------------------------------

def _wait_for_ticket(client, token, seat_id, timeout=15):
    """
    The worker runs in the background — poll to wait for the ticket.

    ⚠️ Avoided fixed `sleep`. It causes flakiness on slow machines and wastes time on fast ones.
    """
    import time

    deadline = time.time() + timeout
    while time.time() < deadline:
        bookings = client.get("/api/bookings", headers=auth_headers(token)).json()
        mine = [b for b in bookings if b["seat_id"] == seat_id and b["status"] == "confirmed"]
        if mine and mine[0]["ticket_status"] != "pending":
            return mine[0]
        time.sleep(0.4)
    return None


def test_booking_starts_with_a_pending_ticket(client, tokens, free_seat):
    """
    Booking is confirmed immediately — the ticket is generated later.

    ⭐ This is the whole point of this phase: the API does not make the user wait for 2-3 seconds.
    """
    seat_id = free_seat["id"]
    res = client.post("/api/bookings", json={"seat_id": seat_id}, headers=auth_headers(tokens[0]))
    assert res.status_code == 201

    bookings = client.get("/api/bookings", headers=auth_headers(tokens[0])).json()
    mine = [b for b in bookings if b["seat_id"] == seat_id][0]
    assert mine["ticket_status"] in ("pending", "ready")


def test_worker_generates_a_downloadable_ticket(client, tokens, free_seat):
    """End-to-end: booking → worker → PDF download."""
    seat_id = free_seat["id"]
    token = tokens[0]

    client.post("/api/bookings", json={"seat_id": seat_id}, headers=auth_headers(token))

    booking = _wait_for_ticket(client, token, seat_id)
    if booking is None:
        pytest.skip("Is the worker running? `docker compose up -d worker`")

    assert booking["ticket_status"] == "ready"

    res = client.get(f"/api/bookings/{booking['id']}/ticket", headers=auth_headers(token))
    assert res.status_code == 200
    assert res.headers["content-type"] == "application/pdf"
    # Is it a real PDF? Check the header — status 200 is not enough.
    assert res.content[:5] == b"%PDF-"
    assert len(res.content) > 1000


def test_cannot_download_someone_elses_ticket(client, tokens, free_seat):
    """
    ⚠️ The most critical ticket test.

    The ticket contains a QR code. Downloading someone else's ticket = free entry.
    """
    seat_id = free_seat["id"]
    owner, attacker = tokens[0], tokens[1]

    client.post("/api/bookings", json={"seat_id": seat_id}, headers=auth_headers(owner))
    booking = _wait_for_ticket(client, owner, seat_id)
    if booking is None:
        pytest.skip("Worker is not running")

    res = client.get(f"/api/bookings/{booking['id']}/ticket", headers=auth_headers(attacker))
    assert res.status_code == 404      # Not 403 — hiding existence


def test_ticket_needs_authentication(client, tokens, free_seat):
    seat_id = free_seat["id"]
    client.post("/api/bookings", json={"seat_id": seat_id}, headers=auth_headers(tokens[0]))
    booking = _wait_for_ticket(client, tokens[0], seat_id)
    if booking is None:
        pytest.skip("Worker is not running")

    assert client.get(f"/api/bookings/{booking['id']}/ticket").status_code == 401


def test_qr_token_is_not_the_booking_id(client, tokens, free_seat):
    """
    ⚠️ The QR should not contain a sequential ID — anyone could generate a QR for 1, 2, or 3 and enter the gate.
    """
    from sqlalchemy import select

    seat_id = free_seat["id"]
    client.post("/api/bookings", json={"seat_id": seat_id}, headers=auth_headers(tokens[0]))
    booking = _wait_for_ticket(client, tokens[0], seat_id)
    if booking is None:
        pytest.skip("Worker is not running")

    # The token is in the DB and is long/random.
    from database import SessionLocal
    from models import Booking

    db = SessionLocal()
    try:
        row = db.get(Booking, booking["id"])
        assert row.qr_token
        assert len(row.qr_token) >= 24
        assert str(booking["id"]) != row.qr_token
    finally:
        db.close()


# ---------------------------------------------------------------------------
# Gate check-in
# ---------------------------------------------------------------------------

def _booked_with_ticket(client, token, seat_id):
    """Book and wait for the ticket to be ready — return the QR token."""
    client.post("/api/bookings", json={"seat_id": seat_id}, headers=auth_headers(token))
    booking = _wait_for_ticket(client, token, seat_id)
    if booking is None or booking["ticket_status"] != "ready":
        pytest.skip("Worker is not running")

    from database import SessionLocal
    from models import Booking

    db = SessionLocal()
    try:
        return booking, db.get(Booking, booking["id"]).qr_token
    finally:
        db.close()


def test_valid_ticket_checks_in(client, tokens, role_tokens, free_seat):
    seat_id = free_seat["id"]
    _, qr = _booked_with_ticket(client, tokens[0], seat_id)

    res = client.post(
        "/api/checkin", json={"token": qr}, headers=auth_headers(role_tokens["organizer"])
    ).json()

    assert res["ok"] is True
    assert res["reason"] == "checked_in"
    assert res["seat_label"]
    assert res["checked_in_at"]


def test_same_qr_cannot_be_used_twice(client, tokens, role_tokens, free_seat):
    """
    ⭐ The core test for this phase.

    If two people take a screenshot of the same QR and go to different gates — neither should be allowed in.
    """
    seat_id = free_seat["id"]
    _, qr = _booked_with_ticket(client, tokens[0], seat_id)
    gate = auth_headers(role_tokens["organizer"])

    first = client.post("/api/checkin", json={"token": qr}, headers=gate).json()
    second = client.post("/api/checkin", json={"token": qr}, headers=gate).json()

    assert first["ok"] is True
    assert second["ok"] is False
    assert second["reason"] == "already_checked_in"
    # The "when" should also be returned on duplicates — this is what is asked at the gate.
    assert second["checked_in_at"] == first["checked_in_at"]


def test_concurrent_scans_admit_exactly_one(client, tokens, role_tokens, free_seat):
    """
    ⭐ The real race — 10 gates simultaneously.

    The same "exactly once" problem as in seat booking, just in a different context.
    """
    seat_id = free_seat["id"]
    _, qr = _booked_with_ticket(client, tokens[0], seat_id)
    gate = auth_headers(role_tokens["organizer"])

    def scan(_):
        return client.post("/api/checkin", json={"token": qr}, headers=gate).json()["reason"]

    with ThreadPoolExecutor(max_workers=10) as pool:
        reasons = list(pool.map(scan, range(10)))

    assert reasons.count("checked_in") == 1, f"More than one entry found: {reasons}"
    assert reasons.count("already_checked_in") == 9


def test_invalid_token_is_rejected(client, role_tokens):
    res = client.post(
        "/api/checkin",
        json={"token": "this-token-does-not-exist-at-all"},
        headers=auth_headers(role_tokens["organizer"]),
    ).json()

    assert res["ok"] is False
    assert res["reason"] == "invalid_ticket"
    # ⚠️ No details should be leaked — otherwise, tokens could be brute-forced.
    assert res["booking_id"] is None
    assert res["seat_label"] is None


def test_attendee_cannot_scan_tickets(client, tokens, role_tokens, free_seat):
    """The gate portal is only for organizers/admins."""
    seat_id = free_seat["id"]
    _, qr = _booked_with_ticket(client, tokens[0], seat_id)

    res = client.post(
        "/api/checkin", json={"token": qr}, headers=auth_headers(role_tokens["attendee"])
    )
    assert res.status_code == 403


def test_cancelled_booking_cannot_check_in(client, tokens, role_tokens, free_seat):
    seat_id = free_seat["id"]
    booking, qr = _booked_with_ticket(client, tokens[0], seat_id)

    client.delete(f"/api/bookings/{booking['id']}", headers=auth_headers(tokens[0]))

    res = client.post(
        "/api/checkin", json={"token": qr}, headers=auth_headers(role_tokens["organizer"])
    ).json()
    assert res["ok"] is False
    assert res["reason"] == "booking_cancelled"


def test_checkin_stats(client, role_tokens):
    res = client.get(
        "/api/checkin/events/1/stats", headers=auth_headers(role_tokens["admin"])
    )
    assert res.status_code == 200
    body = res.json()
    assert body["tickets_sold"] >= body["checked_in"]
    assert body["remaining"] == body["tickets_sold"] - body["checked_in"]
