"""group booking: shares, seat group_held status

Revision ID: 14a521ae0df4
Revises: 8b80a7a62e07
Create Date: 2026-08-30 11:31:11.696013
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14a521ae0df4'
down_revision: Union[str, None] = '8b80a7a62e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ⚠️ group_bookings PEHLE — group_shares ka foreign key isi par hai.
    #
    # Alembic autogenerate ne shares ko pehle rakha tha aur migration
    # `relation "group_bookings" does not exist` se fail hui. Autogenerate
    # dependency order khud nahi samajhta jab dono tables ek hi revision
    # me ban rahi hon.
    op.create_table('group_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('collecting', 'confirmed', 'expired', 'cancelled')", name='ck_group_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_bookings_created_by'), 'group_bookings', ['created_by'], unique=False)
    op.create_index(op.f('ix_group_bookings_event_id'), 'group_bookings', ['event_id'], unique=False)
    op.create_index(op.f('ix_group_bookings_expires_at'), 'group_bookings', ['expires_at'], unique=False)
    op.create_index(op.f('ix_group_bookings_share_token'), 'group_bookings', ['share_token'], unique=True)
    op.create_index(op.f('ix_group_bookings_status'), 'group_bookings', ['status'], unique=False)
    op.create_table('group_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('claimed_by', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("status IN ('unpaid', 'paid', 'refunded')", name='ck_share_status'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claimed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['group_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'seat_id', name='uq_group_seat')
    )
    op.create_index(op.f('ix_group_shares_claimed_by'), 'group_shares', ['claimed_by'], unique=False)
    op.create_index(op.f('ix_group_shares_group_id'), 'group_shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_shares_seat_id'), 'group_shares', ['seat_id'], unique=False)
    op.create_index(op.f('ix_group_shares_status'), 'group_shares', ['status'], unique=False)
    op.add_column('payments', sa.Column('group_share_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_payments_group_share_id'), 'payments', ['group_share_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'group_shares', ['group_share_id'], ['id'], ondelete='SET NULL')
    # ---- ck_seat_status ko naya status sikhana ----
    #
    # ⚠️ Alembic autogenerate ise NAHI pakadta. Wo tables/columns/indexes
    # compare karta hai, par mojooda check constraint ke ANDAR ka text
    # nahi. Yahi Phase 11 me `payment_pending` ke saath bhi hua tha.
    #
    # Bina iske app to chal jayegi, par pehli group booking par
    # `CheckViolation` aayega — aur wo runtime pe milega, migrate pe nahi.
    op.drop_constraint("ck_seat_status", "seats", type_="check")
    op.create_check_constraint(
        "ck_seat_status",
        "seats",
        "status IN ('available', 'locked', 'payment_pending', 'booked', 'group_held')",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade se pehle bachi hui group_held seats ko available karna
    # padta hai, warna purana constraint unhi rows par fail ho jayega.
    op.execute("UPDATE seats SET status = 'available' WHERE status = 'group_held'")
    op.drop_constraint("ck_seat_status", "seats", type_="check")
    op.create_check_constraint(
        "ck_seat_status",
        "seats",
        "status IN ('available', 'locked', 'payment_pending', 'booked')",
    )

    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_group_share_id'), table_name='payments')
    op.drop_column('payments', 'group_share_id')
    op.drop_index(op.f('ix_group_bookings_status'), table_name='group_bookings')
    op.drop_index(op.f('ix_group_bookings_share_token'), table_name='group_bookings')
    op.drop_index(op.f('ix_group_bookings_expires_at'), table_name='group_bookings')
    op.drop_index(op.f('ix_group_bookings_event_id'), table_name='group_bookings')
    op.drop_index(op.f('ix_group_bookings_created_by'), table_name='group_bookings')
    op.drop_table('group_bookings')
    op.drop_index(op.f('ix_group_shares_status'), table_name='group_shares')
    op.drop_index(op.f('ix_group_shares_seat_id'), table_name='group_shares')
    op.drop_index(op.f('ix_group_shares_group_id'), table_name='group_shares')
    op.drop_index(op.f('ix_group_shares_claimed_by'), table_name='group_shares')
    op.drop_table('group_shares')
    # ### end Alembic commands ###
