"""dynamic pricing: event knobs + seat price lock

Revision ID: 8b80a7a62e07
Revises: 51f4bfaeae5c
Create Date: 2026-08-30 05:15:16.188813
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b80a7a62e07'
down_revision: Union[str, None] = '51f4bfaeae5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL column ko server_default ke saath add karte hain.
    #
    # Bina default ke Postgres poochta hai: "purani 40 rows me is column me
    # kya daalun?" -- aur NOT NULL hai to jawab hai NOTHING, migration fail.
    #
    # Default lagate hain, backfill hone dete hain, phir default hata dete
    # hain -- taki aage se application hi value decide kare, DB nahi.
    op.add_column(
        'events',
        sa.Column('dynamic_pricing', sa.Boolean(), nullable=False, server_default='false'),
    )
    op.add_column(
        'events',
        sa.Column('demand_factor', sa.Numeric(4, 2), nullable=False, server_default='0.5'),
    )
    op.add_column(
        'events',
        sa.Column('max_surge', sa.Numeric(4, 2), nullable=False, server_default='2.0'),
    )
    op.alter_column('events', 'dynamic_pricing', server_default=None)
    op.alter_column('events', 'demand_factor', server_default=None)
    op.alter_column('events', 'max_surge', server_default=None)

    # held_price nullable hai -- NULL ka matlab "koi hold nahi, koi price
    # lock nahi". Isliye yahan default ki zaroorat hi nahi.
    op.add_column('seats', sa.Column('held_price', sa.Numeric(10, 2), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'held_price')
    op.drop_column('events', 'max_surge')
    op.drop_column('events', 'demand_factor')
    op.drop_column('events', 'dynamic_pricing')
    # ### end Alembic commands ###
