"""add payments and payment_pending seat status

Revision ID: c84a649f41d1
Revises: 5128a005767c
Create Date: 2026-08-30 04:27:05.264494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c84a649f41d1'
down_revision: Union[str, None] = '5128a005767c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed', 'expired', 'refunded')", name='ck_payment_status'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_status_expires', 'payments', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_payments_event_id'), 'payments', ['event_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=True)
    op.create_index(op.f('ix_payments_seat_id'), 'payments', ['seat_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index('uq_one_pending_payment_per_seat', 'payments', ['seat_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.alter_column(
        "seats", "status",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=24),
        existing_nullable=False,
    )

    # ⚠️ Autogenerate ne ye MISS kiya — wo existing check constraints ka
    # content compare nahi karta.
    #
    # Purani constraint sirf available/locked/booked allow karti hai. Bina
    # ise badle payment_pending insert karte hi CheckViolation aata.
    # Constraints ko "badla" nahi ja sakta — drop karke dobara banana padta hai.
    op.drop_constraint("ck_seat_status", "seats", type_="check")
    op.create_check_constraint(
        "ck_seat_status",
        "seats",
        "status IN ('available', 'locked', 'payment_pending', 'booked')",
    )


def downgrade() -> None:
    # Constraint pehle wapas karo — warna payment_pending wali rows
    # column shrink hone par bhi bachi rahengi aur constraint fail hoga.
    op.execute("UPDATE seats SET status = 'available' WHERE status = 'payment_pending'")
    op.drop_constraint("ck_seat_status", "seats", type_="check")
    op.create_check_constraint(
        "ck_seat_status", "seats", "status IN ('available', 'locked', 'booked')"
    )

    op.alter_column('seats', 'status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_index('uq_one_pending_payment_per_seat', table_name='payments', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_seat_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_event_id'), table_name='payments')
    op.drop_index('ix_payment_status_expires', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
