"""add ticket fields to bookings

Revision ID: 44d84040cffb
Revises: c84a649f41d1
Create Date: 2026-08-30 04:47:29.879973
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44d84040cffb'
down_revision: Union[str, None] = 'c84a649f41d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('qr_token', sa.String(length=64), nullable=True))
    # ⚠️ Recurring issue: NOT NULL columns require a server_default for existing rows.
    # Legacy bookings default to 'pending' for processing by the retry script.
    op.add_column(
        'bookings',
        sa.Column('ticket_status', sa.String(length=16), nullable=False, server_default='pending'),
    )
    op.alter_column('bookings', 'ticket_status', server_default=None)
    op.add_column('bookings', sa.Column('ticket_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bookings_qr_token'), 'bookings', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_qr_token'), table_name='bookings')
    op.drop_column('bookings', 'ticket_generated_at')
    op.drop_column('bookings', 'ticket_status')
    op.drop_column('bookings', 'qr_token')
    # ### end Alembic commands ###
