"""add checkin fields to bookings

Revision ID: 51f4bfaeae5c
Revises: 44d84040cffb
Create Date: 2026-08-30 04:58:42.066261
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51f4bfaeae5c'
down_revision: Union[str, None] = '44d84040cffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('checked_in_by', sa.Integer(), nullable=True))
    # Constraint ko naam diya hai — autogenerate None chhod deta hai, aur
    # bina naam ke downgrade use drop nahi kar sakta.
    op.create_foreign_key(
        'fk_bookings_checked_in_by_users', 'bookings', 'users',
        ['checked_in_by'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_checked_in_by_users', 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'checked_in_by')
    op.drop_column('bookings', 'checked_in_at')
    # ### end Alembic commands ###
