"""add event description and category

Revision ID: 39470c52944a
Revises: 7dcf86fc2ccb
Create Date: 2026-08-15 17:11:47.495866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39470c52944a'
down_revision: Union[str, None] = '7dcf86fc2ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('category', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'category')
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
