"""seat layout: event.layout json + seat.section

Revision ID: df020cc919d7
Revises: 14a521ae0df4
Create Date: 2026-08-30 17:04:58.823206
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df020cc919d7'
down_revision: Union[str, None] = '14a521ae0df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('layout', sa.JSON(), nullable=True))
    op.add_column('seats', sa.Column('section', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'section')
    op.drop_column('events', 'layout')
    # ### end Alembic commands ###
